### ISSUE TITLE
Asi mesiac nefunguje

### ISSUE THREAD

**Issue by johnyb1702** [kodi-czsk/plugin.video.tv.sosac.ph#4]
Videa zo sasaca sa zacnu prehravat, ale asi po 30 sekundach sa vypnu

**Comment by Pooky** [comment]
Sosáč.cz je aktuálně zpoplatněn, musíš si koupit premium a nsatavit username a heslo do addonu. To vypnutí po 30 sekundách tím zmizí. http://tv.sosac.tv/cs/
